# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'TestApp' do
  pod 'PytorchExp', :git=>'https://github.com/xta0/PytorchExp.git' ,:branch => 'master'
end
